### ISSUE TITLE
duplicated devices and wrong json url

### ISSUE THREAD

**Issue by hbakhtiyor** [AndreyBelym/chrome-emulated-devices-list#1]
your json url is wrong, and some duplicated devices listed there, e.g. nexus.
i think this is the [right link](https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/emulated_devices/module.json)

**Comment by AndreyBelym** [comment]
Hi @hbakhtiyor, thanks for pointing me to the right URL. Looks like the file was moved from the previous location two weeks ago: [module.json log](https://chromium.googlesource.com/chromium/src.git/+log/master/third_party/blink/renderer/devtools/front_end/emulated_devices/module.json).

I know about that some devices are duplicated in DB, the reason for this is backward compatibility. Some device names are slightly different in old and new versions of Chrome DevTools. So I've tried not to break compatibility for people that use old device names.
