### ISSUE TITLE
Could someone update the devices on this list?

### ISSUE THREAD

**Issue by chrismjohnston** [AndreyBelym/chrome-emulated-devices-list#5]
I have a Pixel 5, the 5a is out, and the 6 will be here in about a week. Are there any plans to update this list?

**Comment by VasilyStrelyaev** [comment]
I apologize for the late reply. This repository was inadvertently left unmonitored.

Regarding your inquiry, I will mark this issue as an enhancement request. We will take it into account during our future planning.

To address this issue promptly, you are welcome to open a pull request to this repository. Note that you can use the `npm run update` task to automatically fetch the recent device list from the Chromium repository. After you run the `update` task, verify that everything is okay, commit the changes, and open a pull request.
